title: Evan Z Wong
description: Evan Wong Personal Website
theme: null
remote_theme: just-the-docs/just-the-docs@main

plugins:
  - jekyll-remote-theme

url: "https://evanzwong.github.io"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

enable_callouts: true

callouts:
  note:
    title: Note
    color: grey
