title: Evan Z Wong
description: Evan Wong Personal Website
theme: just-the-docs

url: https://tarsythetarsier.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Enable callouts
callouts:
  note:
    title: Note
    color: grey
